name: React Vite CI
on:
  push:
    branches: ['*']
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches: [master]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  workflow_dispatch:
jobs:
  all-cli-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/react-vite
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Set environment variables
        run: mv .env.example .env
      - name: Install dependencies
        run: yarn install
      - name: Build application
        run: yarn build
      - name: Run tests
        run: yarn test
      - name: Run linter
        run: yarn lint
      - name: Check types
        run: yarn check-types
      - name: Build Storybook
        run: yarn build-storybook
      - name: Deploy Storybook
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./apps/react-vite/storybook-static --project-name=bulletproof-react-storybook
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
